let fieldData = {
  goUp: {
    type: "dropdown",
    value: "false",
    label: "Count up",
    options: { true: "Count up", False: "Count down" },
    group: "Customization",
  },
  showPomo: {
    type: "dropdown",
    value: "true",
    label: "Show pomo",
    options: { true: "Yes", False: "No" },
    group: "Customization",
  },
  maxPomos: { type: "number", value: 5, max: 5, step: 1, label: "Max pomos", group: "Customization" },
  targetHours: { type: "number", value: 1, step: 1, label: "Finish hours", group: "Customization" },
  targetMinutes: { type: "number", value: 0, max: 59, step: 1, label: "Finish minutes", group: "Customization" },
  targetSeconds: { type: "number", value: 0, max: 59, step: 1, label: "Finish seconds", group: "Customization" },
  breakHours: { type: "number", value: 0, label: "Break hours", group: "Customization" },
  breakMinutes: { type: "number", value: 0, label: "Break minutes", group: "Customization" },
  breakSeconds: { type: "number", value: 5, label: "Break seconds", group: "Customization" },
  startButton: { type: "button", value: "start", label: "start", group: "Customization" },
  stopButton: { type: "button", value: "stop", label: "stop", group: "Customization" },
  theme: {
    type: "dropdown",
    label: "Theme",
    value: "purple",
    group: "Colors",
    options: {
      purple: "Purple",
      green: "Green",
      pink: "Pink",
      brown: "Brown",
    },
  },
  showCustomColors: {
    type: "dropdown",
    value: "false",
    label: "Use custom colors",
    options: { true: "Yes", false: "No" },
    group: "Colors",
  },
  countdownColor: { type: "colorpicker", value: "#fff", label: "Counter color", group: "Colors" },
  pomoNameColor: { type: "colorpicker", value: "#fff", label: "Pomo text color", group: "Colors" },
  pomoNumbersColor: { type: "colorpicker", value: "#fff", label: "Pomo amount color", group: "Colors" },
  pomoCounterLineColor: {
    type: "colorpicker",
    value: "#fff",
    label: "Separator line color",
    group: "Colors",
  },
  objectiveTextColor: { type: "colorpicker", value: "#8f4ba0", label: "Work/break color", group: "Colors" },
  heartColor: { type: "colorpicker", value: "#8f4ba0", label: "Heart color", group: "Colors" },
  pomoCounterBackgroundColor: {
    type: "colorpicker",
    value: "#df9bf0",
    label: "Pomo counter background color",
    group: "Colors",
  },
  pomoCounterBorderColor: {
    type: "colorpicker",
    value: "#fff",
    label: "Pomo counter border color",
    group: "Colors",
  },
  circleColor: { type: "colorpicker", value: "#8f4ba0", label: "Circles color", group: "Colors" },
  pomoShadowColor: { type: "colorpicker", value: "#8f4ba0", label: "Counter shadow color", group: "Colors" },
}
